services:
  # app:
  #   build: .
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - mongo
  #   env_file:
  #     - .env
  #   environment:
  #     # -----------------------------------------------------------------
  #     - NEXT_PUBLIC_WEB_SOCKET_URL=${NEXT_PUBLIC_WEB_SOCKET_URL}
  #     # -----------------------------------------------------------------
  #     - MONGODB_URI=${MONGODB_URI}
  #     - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
  #     - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
  mongo:
    image: mongo
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    env_file:
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}

volumes:
  mongo-data:
